export * from './lib/engular-base-page.module';
export * from './lib/constants/action-retrieved-type.const';
export * from './lib/models/error-labels-map.interface';
export * from './lib/models/i18n-placeholder-value-maps.interface';
export * from './lib/models/tooltip-map.interface';
export * from './lib/pages-base/base-page/base-page.component';
export * from './lib/pages-base/detail-base-page/detail-base-page.component';
export * from './lib/pages-base/form-base-page/form-base-page.component';
export * from './lib/pages-base/search-base-page/search-base-page.component';
